Add Unmade
nglgzz/awesome-clean-tech pull request #2
Opened 2019-08-02 13:50 UTC by LuRsT

I hope this is the correct category :)

2019-08-03 08:30 UTC, nglgzz requested changes

2019-08-03 08:30 UTC, nglgzz commented on README.md
> +  Unmade is a global fashion software company driving innovation through customisation and delivering an end-to-end digital solution for on-demand production at scale. Unmade was born out of a desire
Hey, thank you for your contribution!

Yup, the category is correct. I will actually rename it to `Social Impact`, as `Awareness` doesn't make its entries justice. Those companies are not just about making people know about problems, but they're also about taking action. 

One thing though, I would update the description to not use buzz words (eg. driving innovation, digital solution) and just explain simply what they do. Here's my suggestion:

```suggestion
Reduces waste in the fashion industry, by offering on-demand production of clothing at scale. Unmade was born out of a desire to re-imagine both the design and manufacturing processes within the fashion industry, so brands only make what is actually sold, resulting in minimal waste.
```

2019-10-01 19:26 UTC, nglgzz commented
Added this entry manually, thank you again for your help!

2019-10-01 19:26 UTC, closed without merging

2019-10-03 11:41 UTC, LuRsT commented
I'm so sorry, I forgot to get back to you, the edit you suggested makes total sense, thanks for manually adding it! :heart: